const About = () => (
  <main className="min-h-[80vh]">
    <title>À propos — Antoine LECA</title>
    <meta name="description" content="Découvrez le parcours d'Antoine LECA, développeur Full Stack passionné par le Mobile First, Tailwind CSS, DaisyUI et les applications web modernes." />

    <div className='divider divider-start pl-6 py-6 text-2xl main-font-m'>À propos</div>
    <div className="flex justify-center items-center flex-col">
      <p className="w-9/10 text-xl mb-4 p-2 lg:p-0">
        Aussi longtemps que je me souvienne : j'ai toujours été dans l'univers et la culture tech, principalement pour du divertissement et notamment les jeux-vidéo. À mes 5-6 ans je regardais par dessus l'épaule de ma grand-mère qui jouait tout le temps à des jeux de stratégie de l'époque : Empereur, La Reine du Nil, Maître de l'Olympe et j'en passe. Depuis, j'ai toujours été proche d'un écran, d'une console. Durant l'adolescense j'ai rapidement développé une "débrouillardise" dès que j'avais un problème avec mes machines : ça pouvait aller de la simple maj de drivers, manipulations du bios pour le mettre à jour jusqu'à le changements de pâte thermique sur ma ps4 et autres travaux d'électronique. J'ai toujours aimé résoudre des problèmes, que ce soit Hardware ou Software léger. Étant proche de bateaux de par ma position géographique mais aussi grâce à des proches en ayant, je me suis rapidement intéressé à la mécanique bateau, les places étant pleines pour la promo de 2nde de cette spécialité je me suis rabattu sur la mécanique auto pensant passer en bateau l'année d'après. J'ai bien aimé le cursus, me creuser la tête, suivre minutieusement un schéma de montage/démontage, l'organisation car après tout : ce sont des choses que je faisais bien avant mon cursus dans le cadre perso lors de mes bidouillages électroniques et autres dépannages que ce soit pour moi ou pour mes proches pour qui j'étais le petit homme de la situation dès qu'il y avait un problème avait el ou tel appareil. Après quelques expériences dans des garages, l'ambiance très "masculine" et irrespectueuse m'a rebuté. Je me suis quand même bien résigné à passer mon bac pro en 2019, que j'ai obtenu, tant pour l'ouverture de portes que le niveau bac peut offrir que pour faire plaisir à ma Maman dégoutée car m'ayant vu louper les 6 derniers mois de ma terminale pour une réinsertion dans le dev, on y vient.

        5 longues années se sont écoulées entre mon premier intérêt pour le dev -pour les mêmes raison que pour la mécanique, ajouter à ceux-là la flexbilité horaire, l'autonomie et le télétrvail- et mon insertion dans une formation. 5 longues années à essayer, plusieurs fois par an, d'apprendre en autodidacte mais ma grande  curiosité, mon goût pour la perfection et le travail bien fait m'a toujours fait me noyer dans la quantité immense de data que l'on peut voir et de langage que l'on peut choisir. Il a fallu d'une info de ma Maman, celle d'un stage organisé par France Travail : "Découverte des métiers du numérique", +/- une semaine par spécialité : Dev Logiciel, Dev Web, Marketing Digital, Impression et modélisation 3D, Montage Vidéo, Design UX/UI. Ce stage m'a permis de découvrir mon goût pour l'UX/UI : mélanger accessibilité, design et user experience collait encore parfaitement aux points énoncés plus haut. Le Webdev m'a aussi grandement plu. Sur conseil des accompagnants lors de ce stage, je me suis orienté vers un cursus Webdev avec pour but de faire un cursus en Design UX/UI et de mélanger les deux par la suite afin d'être de bout en bout dans la chaîne de création d'un site web, du moins en tant que freelance.

        Après une journée porte ouvertes, j'ai pris la décision de m'inscrire en Bachelor à La Plateforme pour la promo 2024 avec le but précis décrit plus haut. 
        D'Octobre à Décembre - Tronc commun : découverte des diverses spécialités proposées par l'école afin de faire un choix après un Hacktahon d'entretiens d'embauche fictifs. Bien entendu : vous savez ce que j'ai choisi. 
        De Janvier à Juin - Spécialisation Web : Au début j'ai fortement galéré, le premier langage touché étant PHP. Mais au fur et à mesure les difficultés commençaient à s'estomper, à l'arrivée de JavaScript j'ai été surpris d'avoir plus de facilité lors de la transition. Et le snowball commençant : 
      </p>
    </div>
  </main>
)

export default About
